// Auto-generated by generate-block-registry.mjs - DO NOT EDIT
// Themes: standalone

import { defineAsyncComponent } from 'vue'

const loadStandalone_AmbientBackground = () => import('~/themes/standalone/components/AmbientBackground.vue')
const Standalone_AmbientBackground = defineAsyncComponent(loadStandalone_AmbientBackground)
const loadStandalone_ArticleList = () => import('~/themes/standalone/components/ArticleList.vue')
const Standalone_ArticleList = defineAsyncComponent(loadStandalone_ArticleList)
const loadStandalone_AsymmetricTileGrid = () => import('~/themes/standalone/components/AsymmetricTileGrid.vue')
const Standalone_AsymmetricTileGrid = defineAsyncComponent(loadStandalone_AsymmetricTileGrid)
const loadStandalone_AudioPlaylist = () => import('~/themes/standalone/components/AudioPlaylist.vue')
const Standalone_AudioPlaylist = defineAsyncComponent(loadStandalone_AudioPlaylist)
const loadStandalone_BeforeAfterReveal = () => import('~/themes/standalone/components/BeforeAfterReveal.vue')
const Standalone_BeforeAfterReveal = defineAsyncComponent(loadStandalone_BeforeAfterReveal)
const loadStandalone_BrandMark = () => import('~/themes/standalone/components/BrandMark.vue')
const Standalone_BrandMark = defineAsyncComponent(loadStandalone_BrandMark)
const loadStandalone_BreadcrumbNav = () => import('~/themes/standalone/components/BreadcrumbNav.vue')
const Standalone_BreadcrumbNav = defineAsyncComponent(loadStandalone_BreadcrumbNav)
const loadStandalone_BroadcastMessage = () => import('~/themes/standalone/components/BroadcastMessage.vue')
const Standalone_BroadcastMessage = defineAsyncComponent(loadStandalone_BroadcastMessage)
const loadStandalone_CanvasBadge = () => import('~/themes/standalone/components/CanvasBadge.vue')
const Standalone_CanvasBadge = defineAsyncComponent(loadStandalone_CanvasBadge)
const loadStandalone_CanvasImage = () => import('~/themes/standalone/components/CanvasImage.vue')
const Standalone_CanvasImage = defineAsyncComponent(loadStandalone_CanvasImage)
const loadStandalone_CanvasShape = () => import('~/themes/standalone/components/CanvasShape.vue')
const Standalone_CanvasShape = defineAsyncComponent(loadStandalone_CanvasShape)
const loadStandalone_CanvasText = () => import('~/themes/standalone/components/CanvasText.vue')
const Standalone_CanvasText = defineAsyncComponent(loadStandalone_CanvasText)
const loadStandalone_CaseStudyCard = () => import('~/themes/standalone/components/CaseStudyCard.vue')
const Standalone_CaseStudyCard = defineAsyncComponent(loadStandalone_CaseStudyCard)
const loadStandalone_CertificationsGrid = () => import('~/themes/standalone/components/CertificationsGrid.vue')
const Standalone_CertificationsGrid = defineAsyncComponent(loadStandalone_CertificationsGrid)
const loadStandalone_ChapterDivider = () => import('~/themes/standalone/components/ChapterDivider.vue')
const Standalone_ChapterDivider = defineAsyncComponent(loadStandalone_ChapterDivider)
const loadStandalone_ChildPageList = () => import('~/themes/standalone/components/ChildPageList.vue')
const Standalone_ChildPageList = defineAsyncComponent(loadStandalone_ChildPageList)
const loadStandalone_ComparisonTable = () => import('~/themes/standalone/components/ComparisonTable.vue')
const Standalone_ComparisonTable = defineAsyncComponent(loadStandalone_ComparisonTable)
const loadStandalone_ContactForm = () => import('~/themes/standalone/components/ContactForm.vue')
const Standalone_ContactForm = defineAsyncComponent(loadStandalone_ContactForm)
const loadStandalone_CreditsList = () => import('~/themes/standalone/components/CreditsList.vue')
const Standalone_CreditsList = defineAsyncComponent(loadStandalone_CreditsList)
const loadStandalone_CTASection = () => import('~/themes/standalone/components/CTASection.vue')
const Standalone_CTASection = defineAsyncComponent(loadStandalone_CTASection)
const loadStandalone_DividerBlock = () => import('~/themes/standalone/components/DividerBlock.vue')
const Standalone_DividerBlock = defineAsyncComponent(loadStandalone_DividerBlock)
const loadStandalone_DocumentList = () => import('~/themes/standalone/components/DocumentList.vue')
const Standalone_DocumentList = defineAsyncComponent(loadStandalone_DocumentList)
const loadStandalone_EditorialComposition = () => import('~/themes/standalone/components/EditorialComposition.vue')
const Standalone_EditorialComposition = defineAsyncComponent(loadStandalone_EditorialComposition)
const loadStandalone_EditorialText = () => import('~/themes/standalone/components/EditorialText.vue')
const Standalone_EditorialText = defineAsyncComponent(loadStandalone_EditorialText)
const loadStandalone_EventCalendar = () => import('~/themes/standalone/components/EventCalendar.vue')
const Standalone_EventCalendar = defineAsyncComponent(loadStandalone_EventCalendar)
const loadStandalone_ExpandingPanels = () => import('~/themes/standalone/components/ExpandingPanels.vue')
const Standalone_ExpandingPanels = defineAsyncComponent(loadStandalone_ExpandingPanels)
const loadStandalone_FaqAccordion = () => import('~/themes/standalone/components/FaqAccordion.vue')
const Standalone_FaqAccordion = defineAsyncComponent(loadStandalone_FaqAccordion)
const loadStandalone_FaqItem = () => import('~/themes/standalone/components/FaqItem.vue')
const Standalone_FaqItem = defineAsyncComponent(loadStandalone_FaqItem)
const loadStandalone_FigureCaption = () => import('~/themes/standalone/components/FigureCaption.vue')
const Standalone_FigureCaption = defineAsyncComponent(loadStandalone_FigureCaption)
const loadStandalone_FilterableGallery = () => import('~/themes/standalone/components/FilterableGallery.vue')
const Standalone_FilterableGallery = defineAsyncComponent(loadStandalone_FilterableGallery)
const loadStandalone_Footer = () => import('~/themes/standalone/components/Footer.vue')
const Standalone_Footer = defineAsyncComponent(loadStandalone_Footer)
const loadShared_FormField = () => import('~/shared/components/FormField.vue')
const Shared_FormField = defineAsyncComponent(loadShared_FormField)
const loadStandalone_GridBlock = () => import('~/themes/standalone/components/GridBlock.vue')
const Standalone_GridBlock = defineAsyncComponent(loadStandalone_GridBlock)
const loadStandalone_Header = () => import('~/themes/standalone/components/Header.vue')
const Standalone_Header = defineAsyncComponent(loadStandalone_Header)
const loadStandalone_HeroBlock = () => import('~/themes/standalone/components/HeroBlock.vue')
const Standalone_HeroBlock = defineAsyncComponent(loadStandalone_HeroBlock)
const loadStandalone_HorizontalScroll = () => import('~/themes/standalone/components/HorizontalScroll.vue')
const Standalone_HorizontalScroll = defineAsyncComponent(loadStandalone_HorizontalScroll)
const loadStandalone_IconGridBlock = () => import('~/themes/standalone/components/IconGridBlock.vue')
const Standalone_IconGridBlock = defineAsyncComponent(loadStandalone_IconGridBlock)
const loadStandalone_ImageBanner = () => import('~/themes/standalone/components/ImageBanner.vue')
const Standalone_ImageBanner = defineAsyncComponent(loadStandalone_ImageBanner)
const loadStandalone_ImageHotspots = () => import('~/themes/standalone/components/ImageHotspots.vue')
const Standalone_ImageHotspots = defineAsyncComponent(loadStandalone_ImageHotspots)
const loadStandalone_ImageSequence = () => import('~/themes/standalone/components/ImageSequence.vue')
const Standalone_ImageSequence = defineAsyncComponent(loadStandalone_ImageSequence)
const loadStandalone_ImageTrail = () => import('~/themes/standalone/components/ImageTrail.vue')
const Standalone_ImageTrail = defineAsyncComponent(loadStandalone_ImageTrail)
const loadStandalone_ItemGridBlock = () => import('~/themes/standalone/components/ItemGridBlock.vue')
const Standalone_ItemGridBlock = defineAsyncComponent(loadStandalone_ItemGridBlock)
const loadStandalone_KineticText = () => import('~/themes/standalone/components/KineticText.vue')
const Standalone_KineticText = defineAsyncComponent(loadStandalone_KineticText)
const loadStandalone_LayeredComposition = () => import('~/themes/standalone/components/LayeredComposition.vue')
const Standalone_LayeredComposition = defineAsyncComponent(loadStandalone_LayeredComposition)
const loadStandalone_LoginForm = () => import('~/themes/standalone/components/LoginForm.vue')
const Standalone_LoginForm = defineAsyncComponent(loadStandalone_LoginForm)
const loadStandalone_LogoWall = () => import('~/themes/standalone/components/LogoWall.vue')
const Standalone_LogoWall = defineAsyncComponent(loadStandalone_LogoWall)
const loadStandalone_MapEmbed = () => import('~/themes/standalone/components/MapEmbed.vue')
const Standalone_MapEmbed = defineAsyncComponent(loadStandalone_MapEmbed)
const loadStandalone_MarqueeBlock = () => import('~/themes/standalone/components/MarqueeBlock.vue')
const Standalone_MarqueeBlock = defineAsyncComponent(loadStandalone_MarqueeBlock)
const loadStandalone_MaterialsBoard = () => import('~/themes/standalone/components/MaterialsBoard.vue')
const Standalone_MaterialsBoard = defineAsyncComponent(loadStandalone_MaterialsBoard)
const loadStandalone_MetadataRow = () => import('~/themes/standalone/components/MetadataRow.vue')
const Standalone_MetadataRow = defineAsyncComponent(loadStandalone_MetadataRow)
const loadStandalone_NarrativeScene = () => import('~/themes/standalone/components/NarrativeScene.vue')
const Standalone_NarrativeScene = defineAsyncComponent(loadStandalone_NarrativeScene)
const loadStandalone_Notification = () => import('~/themes/standalone/components/Notification.vue')
const Standalone_Notification = defineAsyncComponent(loadStandalone_Notification)
const loadStandalone_PageHeader = () => import('~/themes/standalone/components/PageHeader.vue')
const Standalone_PageHeader = defineAsyncComponent(loadStandalone_PageHeader)
const loadStandalone_ProcessSteps = () => import('~/themes/standalone/components/ProcessSteps.vue')
const Standalone_ProcessSteps = defineAsyncComponent(loadStandalone_ProcessSteps)
const loadStandalone_ProfileGrid = () => import('~/themes/standalone/components/ProfileGrid.vue')
const Standalone_ProfileGrid = defineAsyncComponent(loadStandalone_ProfileGrid)
const loadStandalone_ProjectIndex = () => import('~/themes/standalone/components/ProjectIndex.vue')
const Standalone_ProjectIndex = defineAsyncComponent(loadStandalone_ProjectIndex)
const loadStandalone_ProjectPager = () => import('~/themes/standalone/components/ProjectPager.vue')
const Standalone_ProjectPager = defineAsyncComponent(loadStandalone_ProjectPager)
const loadStandalone_PullQuote = () => import('~/themes/standalone/components/PullQuote.vue')
const Standalone_PullQuote = defineAsyncComponent(loadStandalone_PullQuote)
const loadStandalone_QrCode = () => import('~/themes/standalone/components/QrCode.vue')
const Standalone_QrCode = defineAsyncComponent(loadStandalone_QrCode)
const loadStandalone_ScatterCollage = () => import('~/themes/standalone/components/ScatterCollage.vue')
const Standalone_ScatterCollage = defineAsyncComponent(loadStandalone_ScatterCollage)
const loadStandalone_ScrollColorReveal = () => import('~/themes/standalone/components/ScrollColorReveal.vue')
const Standalone_ScrollColorReveal = defineAsyncComponent(loadStandalone_ScrollColorReveal)
const loadStandalone_ScrollReadAlong = () => import('~/themes/standalone/components/ScrollReadAlong.vue')
const Standalone_ScrollReadAlong = defineAsyncComponent(loadStandalone_ScrollReadAlong)
const loadStandalone_SearchBar = () => import('~/themes/standalone/components/SearchBar.vue')
const Standalone_SearchBar = defineAsyncComponent(loadStandalone_SearchBar)
const loadStandalone_SectionHeading = () => import('~/themes/standalone/components/SectionHeading.vue')
const Standalone_SectionHeading = defineAsyncComponent(loadStandalone_SectionHeading)
const loadStandalone_ServicePanel = () => import('~/themes/standalone/components/ServicePanel.vue')
const Standalone_ServicePanel = defineAsyncComponent(loadStandalone_ServicePanel)
const loadStandalone_SideBySideEditorial = () => import('~/themes/standalone/components/SideBySideEditorial.vue')
const Standalone_SideBySideEditorial = defineAsyncComponent(loadStandalone_SideBySideEditorial)
const loadStandalone_SpotlightReveal = () => import('~/themes/standalone/components/SpotlightReveal.vue')
const Standalone_SpotlightReveal = defineAsyncComponent(loadStandalone_SpotlightReveal)
const loadStandalone_StackedCards = () => import('~/themes/standalone/components/StackedCards.vue')
const Standalone_StackedCards = defineAsyncComponent(loadStandalone_StackedCards)
const loadStandalone_StatCounter = () => import('~/themes/standalone/components/StatCounter.vue')
const Standalone_StatCounter = defineAsyncComponent(loadStandalone_StatCounter)
const loadStandalone_StaticCarousel = () => import('~/themes/standalone/components/StaticCarousel.vue')
const Standalone_StaticCarousel = defineAsyncComponent(loadStandalone_StaticCarousel)
const loadStandalone_TableOfContents = () => import('~/themes/standalone/components/TableOfContents.vue')
const Standalone_TableOfContents = defineAsyncComponent(loadStandalone_TableOfContents)
const loadStandalone_Tabs = () => import('~/themes/standalone/components/Tabs.vue')
const Standalone_Tabs = defineAsyncComponent(loadStandalone_Tabs)
const loadStandalone_Testimonials = () => import('~/themes/standalone/components/Testimonials.vue')
const Standalone_Testimonials = defineAsyncComponent(loadStandalone_Testimonials)
const loadStandalone_TextCardBlock = () => import('~/themes/standalone/components/TextCardBlock.vue')
const Standalone_TextCardBlock = defineAsyncComponent(loadStandalone_TextCardBlock)
const loadStandalone_TextSection = () => import('~/themes/standalone/components/TextSection.vue')
const Standalone_TextSection = defineAsyncComponent(loadStandalone_TextSection)
const loadStandalone_TextSplit = () => import('~/themes/standalone/components/TextSplit.vue')
const Standalone_TextSplit = defineAsyncComponent(loadStandalone_TextSplit)
const loadStandalone_Timeline = () => import('~/themes/standalone/components/Timeline.vue')
const Standalone_Timeline = defineAsyncComponent(loadStandalone_Timeline)
const loadStandalone_VideoBlock = () => import('~/themes/standalone/components/VideoBlock.vue')
const Standalone_VideoBlock = defineAsyncComponent(loadStandalone_VideoBlock)

const standaloneRegistry = {
  'ambient-background': {
    component: Standalone_AmbientBackground,
    load: loadStandalone_AmbientBackground,
    type: 'ambient-background',
    componentName: 'AmbientBackground',
  },
  'article-list': {
    component: Standalone_ArticleList,
    load: loadStandalone_ArticleList,
    type: 'article-list',
    componentName: 'ArticleList',
  },
  'asymmetric-tile-grid': {
    component: Standalone_AsymmetricTileGrid,
    load: loadStandalone_AsymmetricTileGrid,
    type: 'asymmetric-tile-grid',
    componentName: 'AsymmetricTileGrid',
  },
  'audio-playlist': {
    component: Standalone_AudioPlaylist,
    load: loadStandalone_AudioPlaylist,
    type: 'audio-playlist',
    componentName: 'AudioPlaylist',
  },
  'before-after-reveal': {
    component: Standalone_BeforeAfterReveal,
    load: loadStandalone_BeforeAfterReveal,
    type: 'before-after-reveal',
    componentName: 'BeforeAfterReveal',
  },
  'brand-mark': {
    component: Standalone_BrandMark,
    load: loadStandalone_BrandMark,
    type: 'brand-mark',
    componentName: 'BrandMark',
  },
  'breadcrumb-nav': {
    component: Standalone_BreadcrumbNav,
    load: loadStandalone_BreadcrumbNav,
    type: 'breadcrumb-nav',
    componentName: 'BreadcrumbNav',
  },
  'broadcast-message': {
    component: Standalone_BroadcastMessage,
    load: loadStandalone_BroadcastMessage,
    type: 'broadcast-message',
    componentName: 'BroadcastMessage',
  },
  'canvas-badge': {
    component: Standalone_CanvasBadge,
    load: loadStandalone_CanvasBadge,
    type: 'canvas-badge',
    componentName: 'CanvasBadge',
  },
  'canvas-image': {
    component: Standalone_CanvasImage,
    load: loadStandalone_CanvasImage,
    type: 'canvas-image',
    componentName: 'CanvasImage',
  },
  'canvas-shape': {
    component: Standalone_CanvasShape,
    load: loadStandalone_CanvasShape,
    type: 'canvas-shape',
    componentName: 'CanvasShape',
  },
  'canvas-text': {
    component: Standalone_CanvasText,
    load: loadStandalone_CanvasText,
    type: 'canvas-text',
    componentName: 'CanvasText',
  },
  'case-study-card': {
    component: Standalone_CaseStudyCard,
    load: loadStandalone_CaseStudyCard,
    type: 'case-study-card',
    componentName: 'CaseStudyCard',
  },
  'certifications-grid': {
    component: Standalone_CertificationsGrid,
    load: loadStandalone_CertificationsGrid,
    type: 'certifications-grid',
    componentName: 'CertificationsGrid',
  },
  'chapter-divider': {
    component: Standalone_ChapterDivider,
    load: loadStandalone_ChapterDivider,
    type: 'chapter-divider',
    componentName: 'ChapterDivider',
  },
  'child-page-list': {
    component: Standalone_ChildPageList,
    load: loadStandalone_ChildPageList,
    type: 'child-page-list',
    componentName: 'ChildPageList',
  },
  'comparison-table': {
    component: Standalone_ComparisonTable,
    load: loadStandalone_ComparisonTable,
    type: 'comparison-table',
    componentName: 'ComparisonTable',
  },
  'contact-form': {
    component: Standalone_ContactForm,
    load: loadStandalone_ContactForm,
    type: 'contact-form',
    componentName: 'ContactForm',
    events: ["submit"],
  },
  'credits-list': {
    component: Standalone_CreditsList,
    load: loadStandalone_CreditsList,
    type: 'credits-list',
    componentName: 'CreditsList',
  },
  'cta-section': {
    component: Standalone_CTASection,
    load: loadStandalone_CTASection,
    type: 'cta-section',
    componentName: 'CTASection',
  },
  'divider-block': {
    component: Standalone_DividerBlock,
    load: loadStandalone_DividerBlock,
    type: 'divider-block',
    componentName: 'DividerBlock',
  },
  'document-list': {
    component: Standalone_DocumentList,
    load: loadStandalone_DocumentList,
    type: 'document-list',
    componentName: 'DocumentList',
  },
  'editorial-composition': {
    component: Standalone_EditorialComposition,
    load: loadStandalone_EditorialComposition,
    type: 'editorial-composition',
    componentName: 'EditorialComposition',
  },
  'editorial-text': {
    component: Standalone_EditorialText,
    load: loadStandalone_EditorialText,
    type: 'editorial-text',
    componentName: 'EditorialText',
  },
  'event-calendar': {
    component: Standalone_EventCalendar,
    load: loadStandalone_EventCalendar,
    type: 'event-calendar',
    componentName: 'EventCalendar',
  },
  'expanding-panels': {
    component: Standalone_ExpandingPanels,
    load: loadStandalone_ExpandingPanels,
    type: 'expanding-panels',
    componentName: 'ExpandingPanels',
  },
  'faq-accordion': {
    component: Standalone_FaqAccordion,
    load: loadStandalone_FaqAccordion,
    type: 'faq-accordion',
    componentName: 'FaqAccordion',
  },
  'faq-item': {
    component: Standalone_FaqItem,
    load: loadStandalone_FaqItem,
    type: 'faq-item',
    componentName: 'FaqItem',
  },
  'figure-caption': {
    component: Standalone_FigureCaption,
    load: loadStandalone_FigureCaption,
    type: 'figure-caption',
    componentName: 'FigureCaption',
  },
  'filterable-gallery': {
    component: Standalone_FilterableGallery,
    load: loadStandalone_FilterableGallery,
    type: 'filterable-gallery',
    componentName: 'FilterableGallery',
  },
  'footer': {
    component: Standalone_Footer,
    load: loadStandalone_Footer,
    type: 'footer',
    componentName: 'Footer',
  },
  'form-field': {
    component: Shared_FormField,
    load: loadShared_FormField,
    type: 'form-field',
    componentName: 'FormField',
  },
  'grid-block': {
    component: Standalone_GridBlock,
    load: loadStandalone_GridBlock,
    type: 'grid-block',
    componentName: 'GridBlock',
  },
  'header': {
    component: Standalone_Header,
    load: loadStandalone_Header,
    type: 'header',
    componentName: 'Header',
  },
  'hero-block': {
    component: Standalone_HeroBlock,
    load: loadStandalone_HeroBlock,
    type: 'hero-block',
    componentName: 'HeroBlock',
  },
  'horizontal-scroll': {
    component: Standalone_HorizontalScroll,
    load: loadStandalone_HorizontalScroll,
    type: 'horizontal-scroll',
    componentName: 'HorizontalScroll',
  },
  'icon-grid-block': {
    component: Standalone_IconGridBlock,
    load: loadStandalone_IconGridBlock,
    type: 'icon-grid-block',
    componentName: 'IconGridBlock',
  },
  'image-banner': {
    component: Standalone_ImageBanner,
    load: loadStandalone_ImageBanner,
    type: 'image-banner',
    componentName: 'ImageBanner',
  },
  'image-hotspots': {
    component: Standalone_ImageHotspots,
    load: loadStandalone_ImageHotspots,
    type: 'image-hotspots',
    componentName: 'ImageHotspots',
  },
  'image-sequence': {
    component: Standalone_ImageSequence,
    load: loadStandalone_ImageSequence,
    type: 'image-sequence',
    componentName: 'ImageSequence',
  },
  'image-trail': {
    component: Standalone_ImageTrail,
    load: loadStandalone_ImageTrail,
    type: 'image-trail',
    componentName: 'ImageTrail',
  },
  'item-grid-block': {
    component: Standalone_ItemGridBlock,
    load: loadStandalone_ItemGridBlock,
    type: 'item-grid-block',
    componentName: 'ItemGridBlock',
  },
  'kinetic-text': {
    component: Standalone_KineticText,
    load: loadStandalone_KineticText,
    type: 'kinetic-text',
    componentName: 'KineticText',
  },
  'layered-composition': {
    component: Standalone_LayeredComposition,
    load: loadStandalone_LayeredComposition,
    type: 'layered-composition',
    componentName: 'LayeredComposition',
  },
  'login-form': {
    component: Standalone_LoginForm,
    load: loadStandalone_LoginForm,
    type: 'login-form',
    componentName: 'LoginForm',
  },
  'logo-wall': {
    component: Standalone_LogoWall,
    load: loadStandalone_LogoWall,
    type: 'logo-wall',
    componentName: 'LogoWall',
  },
  'map-embed': {
    component: Standalone_MapEmbed,
    load: loadStandalone_MapEmbed,
    type: 'map-embed',
    componentName: 'MapEmbed',
  },
  'marquee-block': {
    component: Standalone_MarqueeBlock,
    load: loadStandalone_MarqueeBlock,
    type: 'marquee-block',
    componentName: 'MarqueeBlock',
  },
  'materials-board': {
    component: Standalone_MaterialsBoard,
    load: loadStandalone_MaterialsBoard,
    type: 'materials-board',
    componentName: 'MaterialsBoard',
  },
  'metadata-row': {
    component: Standalone_MetadataRow,
    load: loadStandalone_MetadataRow,
    type: 'metadata-row',
    componentName: 'MetadataRow',
  },
  'narrative-scene': {
    component: Standalone_NarrativeScene,
    load: loadStandalone_NarrativeScene,
    type: 'narrative-scene',
    componentName: 'NarrativeScene',
  },
  'notification': {
    component: Standalone_Notification,
    load: loadStandalone_Notification,
    type: 'notification',
    componentName: 'Notification',
  },
  'page-header': {
    component: Standalone_PageHeader,
    load: loadStandalone_PageHeader,
    type: 'page-header',
    componentName: 'PageHeader',
  },
  'process-steps': {
    component: Standalone_ProcessSteps,
    load: loadStandalone_ProcessSteps,
    type: 'process-steps',
    componentName: 'ProcessSteps',
  },
  'profile-grid': {
    component: Standalone_ProfileGrid,
    load: loadStandalone_ProfileGrid,
    type: 'profile-grid',
    componentName: 'ProfileGrid',
  },
  'project-index': {
    component: Standalone_ProjectIndex,
    load: loadStandalone_ProjectIndex,
    type: 'project-index',
    componentName: 'ProjectIndex',
  },
  'project-pager': {
    component: Standalone_ProjectPager,
    load: loadStandalone_ProjectPager,
    type: 'project-pager',
    componentName: 'ProjectPager',
  },
  'pull-quote': {
    component: Standalone_PullQuote,
    load: loadStandalone_PullQuote,
    type: 'pull-quote',
    componentName: 'PullQuote',
  },
  'qr-code': {
    component: Standalone_QrCode,
    load: loadStandalone_QrCode,
    type: 'qr-code',
    componentName: 'QrCode',
  },
  'scatter-collage': {
    component: Standalone_ScatterCollage,
    load: loadStandalone_ScatterCollage,
    type: 'scatter-collage',
    componentName: 'ScatterCollage',
  },
  'scroll-color-reveal': {
    component: Standalone_ScrollColorReveal,
    load: loadStandalone_ScrollColorReveal,
    type: 'scroll-color-reveal',
    componentName: 'ScrollColorReveal',
  },
  'scroll-read-along': {
    component: Standalone_ScrollReadAlong,
    load: loadStandalone_ScrollReadAlong,
    type: 'scroll-read-along',
    componentName: 'ScrollReadAlong',
  },
  'search-bar': {
    component: Standalone_SearchBar,
    load: loadStandalone_SearchBar,
    type: 'search-bar',
    componentName: 'SearchBar',
  },
  'section-heading': {
    component: Standalone_SectionHeading,
    load: loadStandalone_SectionHeading,
    type: 'section-heading',
    componentName: 'SectionHeading',
  },
  'service-panel': {
    component: Standalone_ServicePanel,
    load: loadStandalone_ServicePanel,
    type: 'service-panel',
    componentName: 'ServicePanel',
  },
  'side-by-side-editorial': {
    component: Standalone_SideBySideEditorial,
    load: loadStandalone_SideBySideEditorial,
    type: 'side-by-side-editorial',
    componentName: 'SideBySideEditorial',
  },
  'spotlight-reveal': {
    component: Standalone_SpotlightReveal,
    load: loadStandalone_SpotlightReveal,
    type: 'spotlight-reveal',
    componentName: 'SpotlightReveal',
  },
  'stacked-cards': {
    component: Standalone_StackedCards,
    load: loadStandalone_StackedCards,
    type: 'stacked-cards',
    componentName: 'StackedCards',
  },
  'stat-counter': {
    component: Standalone_StatCounter,
    load: loadStandalone_StatCounter,
    type: 'stat-counter',
    componentName: 'StatCounter',
  },
  'static-carousel': {
    component: Standalone_StaticCarousel,
    load: loadStandalone_StaticCarousel,
    type: 'static-carousel',
    componentName: 'StaticCarousel',
  },
  'table-of-contents': {
    component: Standalone_TableOfContents,
    load: loadStandalone_TableOfContents,
    type: 'table-of-contents',
    componentName: 'TableOfContents',
  },
  'tabs': {
    component: Standalone_Tabs,
    load: loadStandalone_Tabs,
    type: 'tabs',
    componentName: 'Tabs',
  },
  'testimonials': {
    component: Standalone_Testimonials,
    load: loadStandalone_Testimonials,
    type: 'testimonials',
    componentName: 'Testimonials',
  },
  'text-card-block': {
    component: Standalone_TextCardBlock,
    load: loadStandalone_TextCardBlock,
    type: 'text-card-block',
    componentName: 'TextCardBlock',
  },
  'text-section': {
    component: Standalone_TextSection,
    load: loadStandalone_TextSection,
    type: 'text-section',
    componentName: 'TextSection',
  },
  'text-split': {
    component: Standalone_TextSplit,
    load: loadStandalone_TextSplit,
    type: 'text-split',
    componentName: 'TextSplit',
  },
  'timeline': {
    component: Standalone_Timeline,
    load: loadStandalone_Timeline,
    type: 'timeline',
    componentName: 'Timeline',
  },
  'video-block': {
    component: Standalone_VideoBlock,
    load: loadStandalone_VideoBlock,
    type: 'video-block',
    componentName: 'VideoBlock',
  },
}

export const blockRegistries: Record<string, Record<string, any>> = {
  'standalone': standaloneRegistry,
}

/** Backward-compatible default export (first theme) */
export const blockRegistry = standaloneRegistry

/**
 * Get the block registry for a specific theme.
 * Returns empty registry on unknown theme and logs console.error — never throws.
 */
export function getBlockRegistry(theme: string): Record<string, any> {
  const registry = blockRegistries[theme]
  if (!registry) {
    const available = Object.keys(blockRegistries).join(', ')
    console.error(
      `[getBlockRegistry] Unknown theme "${theme}". Available: ${available}. Returning empty registry.`,
    )
    return {}
  }
  return registry
}

export type BlockType = keyof typeof standaloneRegistry
